In [18]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer


docs = ['let’s win this',
'team spirit',
'cheer loud and proud',
'champions never give up',
'victory for the brave',
'rohit rohit',
'yuvi yuvi',
'boom boom bumrah',
'india on top',
'unstoppable force'
]

In [19]:
tokenizer = Tokenizer(oov_token='<nothing>')

In [20]:
tokenizer.fit_on_texts(docs)

In [21]:
tokenizer.word_index

{'<nothing>': 1,
 'rohit': 2,
 'yuvi': 3,
 'boom': 4,
 'let’s': 5,
 'win': 6,
 'this': 7,
 'team': 8,
 'spirit': 9,
 'cheer': 10,
 'loud': 11,
 'and': 12,
 'proud': 13,
 'champions': 14,
 'never': 15,
 'give': 16,
 'up': 17,
 'victory': 18,
 'for': 19,
 'the': 20,
 'brave': 21,
 'bumrah': 22,
 'india': 23,
 'on': 24,
 'top': 25,
 'unstoppable': 26,
 'force': 27}

In [46]:
len(tokenizer.word_counts)

26

In [23]:
tokenizer.document_count

10

In [24]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[5, 6, 7],
 [8, 9],
 [10, 11, 12, 13],
 [14, 15, 16, 17],
 [18, 19, 20, 21],
 [2, 2],
 [3, 3],
 [4, 4, 22],
 [23, 24, 25],
 [26, 27]]

In [25]:
from tensorflow.keras.utils import pad_sequences
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [41]:
sequences = pad_sequences(sequences,padding='post')
sequences

array([[ 5,  6,  7,  0],
       [ 8,  9,  0,  0],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [ 2,  2,  0,  0],
       [ 3,  3,  0,  0],
       [ 4,  4, 22,  0],
       [23, 24, 25,  0],
       [26, 27,  0,  0]], dtype=int32)

In [53]:
#this is just to show how the embedding will work and how the output will be, this will go as input to RNN

model = Sequential()
model.add(Embedding(len(tokenizer.word_index) + 1,output_dim=2,input_length=4))

#27 is the total vocabulary size of the data
#2 is the size of the embedding that it outputs
#input length is the length of the sentence(each sentence has token size of 4)

model.compile('adam','accuracy')
pred = model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step
[[[-0.02114451 -0.00693255]
  [ 0.00385623 -0.03393143]
  [-0.01481849 -0.01782542]
  [-0.01177373 -0.00139461]]

 [[-0.03098476 -0.0136076 ]
  [ 0.04008241 -0.01832151]
  [-0.01177373 -0.00139461]
  [-0.01177373 -0.00139461]]

 [[-0.03977339  0.00536208]
  [-0.0110826  -0.00837468]
  [-0.02252886 -0.01368626]
  [-0.02598659  0.04191611]]

 [[-0.03224351 -0.02935399]
  [-0.0393079   0.00816391]
  [-0.0496605   0.04118435]
  [ 0.03418286  0.02109588]]

 [[ 0.00800309 -0.04100944]
  [ 0.01515051  0.01618919]
  [ 0.00054721  0.04782363]
  [ 0.01212736 -0.01838906]]

 [[ 0.01981897  0.00486211]
  [ 0.01981897  0.00486211]
  [-0.01177373 -0.00139461]
  [-0.01177373 -0.00139461]]

 [[ 0.03960109 -0.02920917]
  [ 0.03960109 -0.02920917]
  [-0.01177373 -0.00139461]
  [-0.01177373 -0.00139461]]

 [[ 0.02686599 -0.01221006]
  [ 0.02686599 -0.01221006]
  [-0.01701404 -0.02254988]
  [-0.01177373 -0.00139461]]

 [[ 0.01623711 -0.01874329]
  [-0.00130374 -0.009

In [52]:
from keras.datasets import imdb
from keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step
[[[-0.04970398 -0.02842243]
  [ 0.01249461 -0.04091763]
  [-0.00894056 -0.04089009]
  [-0.04170324  0.01762564]]

 [[-0.0414704  -0.0103724 ]
  [ 0.03035598 -0.03492467]
  [-0.04170324  0.01762564]
  [-0.04170324  0.01762564]]

 [[ 0.02697888 -0.04915053]
  [ 0.02185354 -0.01127043]
  [-0.00476817 -0.03442337]
  [ 0.01844556 -0.04728407]]

 [[-0.04058265  0.01705519]
  [-0.0177679   0.04214079]
  [-0.02351671 -0.03952732]
  [-0.03313339 -0.03383388]]

 [[-0.02197774  0.04166773]
  [ 0.036772    0.01115628]
  [-0.03867519  0.00253033]
  [-0.02192948  0.00768276]]

 [[-0.00666598  0.02584415]
  [-0.00666598  0.02584415]
  [-0.04170324  0.01762564]
  [-0.04170324  0.01762564]]

 [[-0.03889466 -0.0460838 ]
  [-0.03889466 -0.0460838 ]
  [-0.04170324  0.01762564]
  [-0.04170324  0.01762564]]

 [[-0.04697387  0.0449576 ]
  [-0.04697387  0.0449576 ]
  [-0.00925127  0.02469141]
  [-0.04170324  0.01762564]]

 [[ 0.03155375  0.00807625]
  [-0.03211845 -0.009

In [66]:
(X_train,y_train),(X_test,y_test) = imdb.load_data(num_words=10000)

In [67]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [68]:
model = Sequential()
model.add(Embedding(10000, 2, input_length=50))
model.add(SimpleRNN(32,return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

model.summary()

'''
The Embedding layer in Keras does not use any predefined embedding method like Word2Vec, GloVe, or BERT by default. Instead, it uses:

✅ Random initialization + learned training
The Embedding layer starts with random weights.

During model training, backpropagation updates the weights of the embedding matrix so that each token's vector becomes more useful for the task (e.g., classification, prediction).

So, the process is:
You provide integer-encoded tokens (e.g., [2, 4, 6, 1, 3]).

The Embedding(input_dim=17, output_dim=2) layer creates a lookup table of shape (17, 2) — 17 tokens, each mapped to a 2D vector.

Each input integer index is replaced by its corresponding 2D vector during the forward pass.

These vectors are updated during training via gradient descent.

Summary:
Method used: Randomly initialized, learned embeddings via backpropagation.

Not used: Pretrained embeddings (unless you explicitly load them)

'''

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_17"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_12 (Embedding)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_12 (SimpleRNN)       │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

"\nThe Embedding layer in Keras does not use any predefined embedding method like Word2Vec, GloVe, or BERT by default. Instead, it uses:\n\n✅ Random initialization + learned training\nThe Embedding layer starts with random weights.\n\nDuring model training, backpropagation updates the weights of the embedding matrix so that each token's vector becomes more useful for the task (e.g., classification, prediction).\n\nSo, the process is:\nYou provide integer-encoded tokens (e.g., [2, 4, 6, 1, 3]).\n\nThe Embedding(input_dim=17, output_dim=2) layer creates a lookup table of shape (17, 2) — 17 tokens, each mapped to a 2D vector.\n\nEach input integer index is replaced by its corresponding 2D vector during the forward pass.\n\nThese vectors are updated during training via gradient descent.\n\nSummary:\nMethod used: Randomly initialized, learned embeddings via backpropagation.\n\nNot used: Pretrained embeddings (unless you explicitly load them)\n\n"

In [69]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
history = model.fit(X_train, y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 15s 16ms/step - acc: 0.5237 - loss: 0.6905 - val_acc: 0.7539 - val_loss: 0.5094
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 21s 16ms/step - acc: 0.7981 - loss: 0.4439 - val_acc: 0.8118 - val_loss: 0.4170
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 23s 19ms/step - acc: 0.8713 - loss: 0.3172 - val_acc: 0.7995 - val_loss: 0.4424
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 15s 19ms/step - acc: 0.8963 - loss: 0.2644 - val_acc: 0.7987 - val_loss: 0.4609
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 19s 17ms/step - acc: 0.9172 - loss: 0.2233 - val_acc: 0.7960 - val_loss: 0.4996
